Metrostroi.DefineSystem("U2_panel")

function TRAIN_SYSTEM:Initialize()

    self.Train:LoadSystem("WarningAnnouncement","Relay","Switch", {bass = true})
    self.Train:LoadSystem("Ventilation","Relay","Switch", {bass = true})
    self.Train:LoadSystem("Deadman","Relay","Switch", {bass = true})
    self.Train:LoadSystem("PantoUp","Relay","Switch", {bass = true})
    self.Train:LoadSystem("DoorsUnlock","Relay","Switch", {bass = true})
    self.Train:LoadSystem("DoorsLock","Relay","Switch", {bass = true})
    self.Train:LoadSystem("DoorsCloseConfirm","Relay","Switch", {bass = true})
    self.Train:LoadSystem("DoorsSelectRight","Relay","Switch", {bass = true})
    self.Train:LoadSystem("DoorsSelectLeft","Relay","Switch", {bass = true})
    self.Train:LoadSystem("Battery","Relay","Switch", {bass = true})
    self.Train:LoadSystem("Lights","Relay","Switch", {bass = true})
    self.Train:LoadSystem("WarnBlink","Relay","Switch", {bass = true})
    self.Train:LoadSystem("DriverLight","Relay","Switch", {bass = true})
    self.Train:LoadSystem("BatteryDisable","Relay","Switch", {bass = true})
    self.Train:LoadSystem("BlinkerRight","Relay","Switch", {bass = true})
    self.Train:LoadSystem("PassengerLightsOn","Relay","Switch", {bass = true})
    self.Train:LoadSystem("PassengerLightsOff","Relay","Switch", {bass = true})
    self.Train:LoadSystem("Bell","Relay","Switch", {bass = true})
    self.Train:LoadSystem("Horn","Relay","Switch", {bass = true})

    self.Train:LoadSystem("Number1","Relay","Switch", {bass = true})
    self.Train:LoadSystem("Number2","Relay","Switch", {bass = true})
    self.Train:LoadSystem("Number3","Relay","Switch", {bass = true})
    self.Train:LoadSystem("Number4","Relay","Switch", {bass = true})
    self.Train:LoadSystem("Number5","Relay","Switch", {bass = true})
    self.Train:LoadSystem("Number6","Relay","Switch", {bass = true})
    self.Train:LoadSystem("Number7","Relay","Switch", {bass = true})
    self.Train:LoadSystem("Number8","Relay","Switch", {bass = true})
    self.Train:LoadSystem("Number9","Relay","Switch", {bass = true})
    self.Train:LoadSystem("Number0","Relay","Switch", {bass = true})
    self.Train:LoadSystem("Enter","Relay","Switch", {bass = true})
    self.Train:LoadSystem("Delete","Relay","Switch", {bass = true})
    self.Train:LoadSystem("Destination","Relay","Switch", {bass = true})
    self.Train:LoadSystem("SpecialAnnouncements","Relay","Switch", {bass = true})
    self.Train:LoadSystem("DateAndTime","Relay","Switch", {bass = true})
end