ENT.Type = "anim"
ENT.Author = "LillyWho"
ENT.Contact = ""
ENT.Purpose = ""
ENT.Instructions = "Defines a track rule starting from a specific point on"
ENT.Category = "Metrostroi: Project Light Rail"
ENT.PrintName = "Trackside Signage"
ENT.Spawnable = true
ENT.AdminOnly = true
ENT.BasePath = "models/lilly/uf/signage"
ENT.Types = {
	[ "Bell" ] = "bell",
	[ "Cut Traction" ] = "cut_traction",
	[ "Drop Pantograph" ] = "drop_panto",
	[ "Enable Traction" ] = "enable_traction",
	[ "End of Block Signalling" ] = "end_of_block_operation",
	[ "End of Speed Restriction" ] = "end_of_speed_restriction",
	[ "Catenary Insulation Ahead" ] = "insulator",
	[ "No Oncoming Traffic Allowed" ] = "no_passing_start",
	[ "Oncoming Traffic Allowed" ] = "no_passing_end",
	[ "Switch Trigger Here" ] = "point_contact",
	[ "Raise Pantograph" ] = "raise_panto",
	[ "Safety Stop" ] = "sh1",
	[ "Signal Trigger Here" ] = "signal_contact",
	[ "Speed 10km/h" ] = "speed_10",
	[ "Speed 20km/h" ] = "speed_20",
	[ "Speed 30km/h" ] = "speed_30",
	[ "Speed 40km/h" ] = "speed_40",
	[ "Speed 50km/h" ] = "speed_50",
	[ "Speed 60km/h" ] = "speed_60",
	[ "Speed 70km/h" ] = "speed_70",
	[ "Speed 80km/h" ] = "speed_80",
	[ "Speed Clear" ] = "speed_clear",
	[ "Warning 10km/h" ] = "start_10",
	[ "Warning 20km/h" ] = "start_20",
	[ "Warning 30km/h" ] = "start_30",
	[ "Warning 40km/h" ] = "start_40",
	[ "Warning 50km/h" ] = "start_50",
	[ "Warning 60km/h" ] = "start_60",
	[ "Warning 70km/h" ] = "start_70",
	[ "Warning 80km/h" ] = "start_80",
	[ "Entering Block Operation" ] = "start_of_block_operation",
	[ "Station Stop Marker" ] = "stop_here_station"
}