if SERVER then return end
CreateClientConVar( "mplr_signal_distance", "8192", true, false, "Render Distance for Light Rail Signals" )
CreateClientConVar( "mplr_camera_jerk_intensity", "7.5", true, true, "How much the camera jerks back and forth in reaction to the train's acceleration.", 1, 8 )
CreateClientConVar( "mplr_enable_signal_sprite_scaling", "1", true, true, "Enable or disable distance-based scaling of signal sprites, for visibility. On by default.", 0, 1 )
CreateClientConVar( "mplr_cl_verbose", "1", true, true, "Enable verbose console logging clientside.", 0, 1 )
CreateClientConVar( "mplr_scrollwheel_sensitivity", "1", true, true, "Set the sensitivity of the scroll wheel throttle.", 0, 10 )
CreateClientConVar( "mplr_mirrors_enable", "0", true, true, "Enable or disable rear view mirrors on vehicles.", 0, 1 )
CreateClientConVar( "mplr_mirrors_fps", "60", true, true, "Framerate for virtual mirrors.", 15, 60 )
CreateClientConVar( "mplr_mirrors_resolution", "1", true, true, "Resolution settings for dynamic mirrors.", 1, 3 )
CreateClientConVar( "mplr_lumino_enable", "1", true, true, "Enable or disable rendering the station arrivals displays which may be costly to render.", 0, 1 )
CreateClientConVar( "mplr_lumino_lod", "3", true, true, "Level of Detail factor for rendering the LED dots on the arrivals displays. Higher equals better.", 1, 3 )
concommand.Add( "mplr_manual", function()
	--ply, _, args)
	gui.OpenURL( "https://lillywho.github.io" )
end )

print( "MPLR: Set all the client convars!" )